minetest.register_on_newplayer(function(player)
	player:get_inventory():add_item('main', 'default:pick_steel')
	player:get_inventory():add_item('main', 'default:sword_steel')
	player:get_inventory():add_item('main', 'default:shovel_steel')
	player:get_inventory():add_item('main', 'crafting:workbench')
	player:get_inventory():add_item('main', 'default:torch 8')
	player:get_inventory():add_item('main', 'default:wood 64')
	player:get_inventory():add_item('main', 'default:cobble 64')
end)